pool:
  vmImage: 'ubuntu-latest'

trigger: none
resources:
  pipelines:
    - pipeline: build
      source: 0x0ade.AzurePipelinesSandbox
      trigger: true

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: specific
    project: AzurePipelinesSandbox
    pipeline: 0x0ade.AzurePipelinesSandbox
    specificBuildWithTriggering: true
    downloadType: specific
    downloadPath: $(Build.ArtifactStagingDirectory)
- script: ls -lR $(Build.ArtifactStagingDirectory)

- script: |
    echo "Secondary Pipeline Run Complete"
    echo ${{ resources.pipeline.build.runID }}
    echo ${{ resources.pipeline.build.runName }}
