# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- pwsh: Write-Host "##vso[task.setvariable variable=test_variable]True"
  displayName: 'Set a variable in PowerShell'
- script: echo Variable was assigned
  condition: eq(variables['test_variable'], 'True')
  displayName: 'Read previously assigned variable'

- task: Cache@2
  displayName: Cache with secret as key
  inputs:
    key: '"test-cache" | "$(SECRET_SOMETHING)"'
    path: $(Pipeline.Workspace)/cache
- script: 'mkdir -p $CACHE && echo "cache test $(test_variable)" | tee $CACHE/placeholder.txt'
  env:
    CACHE: $(Pipeline.Workspace)/cache

- task: PublishBuildArtifacts@1
  displayName: 'Publish placeholder artifact'
  continueOnError: true
  inputs:
    pathtoPublish: '$(Pipeline.Workspace)/cache/'
    artifactName: 'placeholder'
    publishLocation: 'Container'

- script: |
    echo "Contents of $(Pipeline.Workspace)/"
    ls -alR $(Pipeline.Workspace)/

    declare -i BUILD_NUMBER=20+20
    echo "##vso[task.setvariable variable=build_number]$BUILD_NUMBER"

- task: GitHubRelease@1
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: '0x0ade-bot'
    repositoryName: '0x0ade/AzurePipelinesSandbox'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v1.$(build_number).0'
    title: 'Stable Build $(build_number)'
    assets: '$(Pipeline.Workspace)/cache/placeholder.txt'
    isDraft: true
    addChangeLog: false
